# Header
navbar_brand: 可愛いを叫ぶブログ
menu:
  - title: Top
    url: index.html
    intro: "ブログトップ"
    icon: "fa fa-home fa-lg"
  - title: Archives
    url: archives
    intro: "過去の記事"
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "カテゴリー一覧"
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "タグ一覧"
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "このブログについて"
    icon: "fa fa-user"
  # Home: index.html
  # Archives: archives/
  # Categories: categories/
  # Tags: tags/
  # About: about/
rss: /sblog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about         # See also: `about_content`
- recent_posts
- category
- tagcloud
- archive
about_widget_content: >
  <p>しらきが可愛いと思うものを可愛いと叫ぶためのブログです。</br>ほぼ藤田咲さん。</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-84876135-2
favicon: favicon.ico
twitter_id: '@shiraki_ii'
google_plus:
fb_admins:
fb_app_id:
